### PR TITLE
Cloud-manager-agent as Helm Chart w/ Terraform Module

### PR DESCRIPTION
**Pull request by jdmaguire**
In the old way we'd configure poolmembers, we'd deploy a bunch of kustomize manifests against the cluster. We're porting them over to helm w/ terraform module. This is the work for cloud-manager-agent.

It's a pretty standard chart.

A statefulset. A headless service. Some config maps for the app.

### CODE REVIEW

**Comment by jdmaguire** [comment]
Still to do:

- [ ] top main.tf changes
- [ ] test
- [ ] Remove some incorrect wording
- [ ] Generate readme

**Comment by jdmaguire** [comment]
Still trying to get this working. Talking to Joey, we decided to add ExternalSecret support. That component is deprecated; I've filled tickets to upgrade to the External Secrets Operator.

https://github.com/streamnative/terraform-google-cloud/issues/5
https://github.com/streamnative/terraform-aws-cloud/issues/62

Trying to get this working on a test cluster with this values file:

```
appConfig:
  applicationAgentProperties:
    kubernetesExternalSecret:
      enabled: true
```

Having some issues. Just recording this all for next week.

**Comment by jdmaguire** [comment]
This code works as-is. There is some discussion one whether we should use the secret raw, have cloud-api-server inject the secret, or use KSE/ESO. This PR could go in before that decision is made.

**Review by jrsdav — APPROVED** [review]
Love it! Great job.

**Comment by jdmaguire** [comment]
Forgot to link to the relevant GH issues. https://github.com/streamnative/cloud-ops/issues/245

https://github.com/streamnative/cloud-api-server/issues/900

**Pull request merged**
